In [121]:
import pandas as pd

In [122]:
data = {
    'Book Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Genre': ['Classic', 'Classic', 'Dystopian', 'Classic', 'Classic'],
    'Price': [10.99, 8.99, 7.99, 11.99, 9.99],
    'Copies Sold': [500, 600, 800, 300, 450]
}

df = pd.DataFrame(data)

In [123]:
df.head(2)

              Book Title               Author    Genre  Price  Copies Sold
0       The Great Gatsby  F. Scott Fitzgerald  Classic  10.99          500
1  To Kill a Mockingbird           Harper Lee  Classic   8.99          600

In [124]:
df.describe()

           Price  Copies Sold
count   5.000000     5.000000
mean    9.990000   530.000000
std     1.581139   185.741756
min     7.990000   300.000000
25%     8.990000   450.000000
50%     9.990000   500.000000
75%    10.990000   600.000000
max    11.990000   800.000000

In [125]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Book Title   5 non-null      str
 1   Author       5 non-null      str
 2   Genre        5 non-null      str
 3   Price        5 non-null      float64
 4   Copies Sold  5 non-null      int64
dtypes: float64(1), int64(1), str(3)
memory usage: 332.0 bytes

In [126]:
df.sort_values("Price")

               Book Title               Author      Genre  Price  Copies Sold
2                    1984        George Orwell  Dystopian   7.99          800
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
3     Pride and Prejudice          Jane Austen    Classic  11.99          300

In [127]:
df['Author']

0    F. Scott Fitzgerald
1             Harper Lee
2          George Orwell
3            Jane Austen
4          J.D. Salinger
Name: Author, dtype: str

In [128]:
sorteddf = df.sort_values(by="Author")
sorteddf

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
2                    1984        George Orwell  Dystopian   7.99          800
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
3     Pride and Prejudice          Jane Austen    Classic  11.99          300

In [129]:
classic_books = df[df['Genre'] == 'Classic']
classic_books['Book Title']

0          The Great Gatsby
1     To Kill a Mockingbird
3       Pride and Prejudice
4    The Catcher in the Rye
Name: Book Title, dtype: str

In [130]:
# df.groupby('Author')

In [131]:
sales_by_author = df.groupby('Author')['Copies Sold'].sum()
print(sales_by_author)

Author
F. Scott Fitzgerald    500
George Orwell          800
Harper Lee             600
J.D. Salinger          450
Jane Austen            300
Name: Copies Sold, dtype: int64

In [132]:
all_sales = df['Copies Sold'].sum()
print(all_sales)

2650

In [133]:
iris_data = pd.read_csv('iris_dataset.csv', header=None)
print(iris_data.head())

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [134]:
iris_data = pd.read_csv('iris_dataset.csv', names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
print(iris_data.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [135]:
json_data = pd.read_json('posts.json')
print(json_data.head())

   userId  id                                              title  \
0       1   1  sunt aut facere repellat provident occaecati e...
1       1   2                                       qui est esse
2       1   3  ea molestias quasi exercitationem repellat qui...
3       1   4                               eum et est occaecati
4       1   5                                 nesciunt quas odio

                                                body
0  quia et suscipit\nsuscipit recusandae consequu...
1  est rerum tempore vitae\nsequi sint nihil repr...
2  et iusto sed quo iure\nvoluptatem occaecati om...
3  ullam et saepe reiciendis voluptatem adipisci\...
4  repudiandae veniam quaerat sunt sed\nalias aut...

In [136]:
excel_data = pd.read_excel('file_example_XLS_10(5).xls', index_col=0)
print(excel_data.head())

  First Name  Last Name  Gender        Country  Age        Date    Id
0
1      Dulce      Abril  Female  United States   32  15/10/2017  1562
2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
3     Philip       Gent    Male         France   36  21/05/2015  2587
4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [137]:
grade_data = pd.read_csv('grades.csv')
# grade_data.head(2)
# grade_data.tail(4)
grade_data.iloc[0]

Last name                   Alfalfa
 "First name"            "Aloysius"
 "SSN"                "123-45-6789"
        "Test1"                40.0
 "Test2"                       90.0
 "Test3"                      100.0
 "Test4"                       83.0
 "Final"                       49.0
 "Grade"                       "D-"
Name: 0, dtype: object

In [138]:
df = pd.DataFrame({
       'Column1': [1, 2, 3, 4, 5],
       'Column2': ['A', 'B', 'C', 'D', 'E'],
       'Column3': [True, False, True, False, True]
   })
df.to_csv('my_dataframe.csv', index=False)

In [139]:
import numpy as np
from faker import Faker
import random

In [140]:
fake=Faker()

In [141]:
# data = [(fake.name(), np.random.randint(18,70)) 
#     for _ in range(100)]
# df = pd.DataFrame(data, columns=['Name', 'Age'])
# print(df.head())

In [142]:
# sales_data = [(fake.word(), np.random.randint(10, 500), fake.date_this_year(), np.random.randint(18, 70)) 
#     for _ in range(500)]
# sales_df = pd.DataFrame(sales_data, 
#     columns=['Product', 'Sale Amount', 'Date of Sale', 'Customer Age'])
# print(sales_df.head())

In [ ]:
sales_data = [
    (
        random.choice(['Products', 'Drinks', 'Clothes', 'Hat']), 
        np.random.randint(50, 1000), 
        fake.name(), 
        np.random.randint(18, 70)) 
    for _ in range(10)
]

sales_df = pd.DataFrame(sales_data, 
    columns=['Category', 'Sale Amount', 'Name Customer', 'Customer Age'])
print(sales_df.head())

   Category  Sale Amount   Name Customer  Customer Age
0    Drinks          829    April Dorsey            54
1  Products          515  Angela Johnson            27
2    Drinks          948    Tyler Berger            59
3    Drinks          832  Michael Taylor            45
4  Products          636     Susan Jones            34

Exercise 1: Introduction to Data Analysis

Data analysis is the process of collecting, cleaning, and studying information in order to understand what is happening and why. Its goal is not only to calculate numbers, but also to find patterns and use them to make better, more informed decisions.

Today, data analysis is important in almost every field because the amount of information is constantly growing. Companies, public organizations, and ordinary users generate data every day, and without analysis, it is often just a collection of numbers. Analytics helps identify problems faster, understand people’s behavior, evaluate performance, and predict possible outcomes.

Data analysis is widely used in business, healthcare, and logistics. In business, it helps companies study sales, customer behavior, and advertising performance to understand what brings profit and what should be improved. In healthcare, data is used to analyze treatment results, disease patterns, and risk factors, which can help improve the quality of care. In logistics, data analysis helps build more efficient routes, reduce costs, and shorten delivery times.

In conclusion, data analysis helps turn large amounts of information into clear and useful insights. That is why it has become an important tool for making decisions in many different areas.